apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: delayjobs.delayjob.k8s.io
  # for more information on the below annotation, please see
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  group: delayjob.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # schema used for validation
        # for more information on the below annotation, please see
        # https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        # enables the status subresource
        status: { }
  names:
    kind: DelayJob
    plural: delayjobs
  scope: Namespaced