apiVersion: delayjob.k8s.io/v1
kind: DelayJob
metadata:
  name: hello
spec:
  execution_time: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:1.28
              command: ["echo", "hello k8s delayjob!"]
          restartPolicy: Never
